name: build keygen

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Make a new release'
        type: boolean
        default: false
      tag:
        description: 'Release tag'
        required: false

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a]
    steps:
      - uses: actions/checkout@v5

      - name: Setup Zig CC
        id: zigcc
        run: |
          curl -L https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz -o zig.tar.xz
          mkdir zig && tar -xf zig.tar.xz -C zig --strip-components=1 && rm -f zig.tar.xz
          echo "zigcc-path=${{ github.workspace }}/zig" >> $GITHUB_OUTPUT

      - name: Download openssl latest release
        run: |
          TAGNAME=$(gh release list -R openssl/openssl --json tagName,isLatest -q '.[] | select(.isLatest) | .tagName')
          gh release download -R openssl/openssl $TAGNAME -p "*.tar.gz" -O openssl.tar.gz
          mkdir openssl && tar -xvf openssl.tar.gz -C openssl --strip-components=1 && rm -rf openssl.tar.gz

      - name: Build openssl
        run: |
          export PATH=$ZIGCC_PATH:$PATH
          mkdir -p out
          cd openssl

          if [ "${{ matrix.arch }}" == "arm64-v8a" ]; then
            TARGET="aarch64-linux"
          else
            TARGET="arm-linux"
          fi

          CC="zig cc -target $TARGET" ./config --prefix="${{ github.workspace }}/out" \
              no-shared no-module no-autoload-config no-asm no-ui-console \
              no-dh no-dsa no-ec2m no-sm2 no-sm3 no-sm4 \
              no-ssl no-tls no-dtls no-engine no-ocsp no-cms no-ts no-psk no-srp no-async no-comp no-nextprotoneg \
              no-aria no-bf no-camellia no-cast no-des no-idea no-rc2 no-rc4 no-rc5 no-seed no-chacha no-poly1305
          make -j$(nproc)
          make install

          cd ..
          mv out/lib* out/lib
        env:
          ZIGCC_PATH: ${{ steps.zigcc.outputs.zigcc-path }}

      - name: Build keygen
        run: |
          mkdir -p build && cd build
          export PATH=$ZIGCC_PATH:$PATH

          if [ "${{ matrix.arch }}" == "arm64-v8a" ]; then
            TARGET="aarch64-linux"
          else
            TARGET="arm-linux"
          fi

          export CC="zig cc -target $TARGET"
          export CXX="zig c++ -target $TARGET"

          cmake ..
          cmake --build .
        env:
          ZIGCC_PATH: ${{ steps.zigcc.outputs.zigcc-path }}

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Compress with UPX
        run: |
          upx --best --lzma build/keygen -o keygen
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: keygen

  release:
    needs: build
    if: github.event.inputs.create_release && github.event.inputs.tag != ''
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Create tar archive
        run: tar -czvf keygen.tar.gz -C artifacts .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: keygen.tar.gz
          tag_name: ${{ github.event.inputs.tag }}
